### ISSUE TITLE
DoH over non standard port

### ISSUE THREAD

**Issue by datatype** [paulmillr/encrypted-dns#21] opened 2020-12-16 18:19 UTC
Unfortunately I need to create a profile for an Inhouse (non-public) DoH proxy. Creating the profile was quite easy by modifying the google profile provided here, but I stuck at the point that I need to run the DoH proxyy on another port than 443. 
Can I define the port somewhere in profile?

**Comment by paulmillr** [comment] 2020-12-16 18:52
did you try something like this?

```
				<key>ServerURL</key>
				<string>https://security.cloudflare-dns.com:42091/dns-query</string>
```

**Comment by datatype** [comment] 2020-12-16 18:55
Yep, it's ignored :-(  The iPad still tries to reach the DoH under :443...

**Comment by BirdInFire** [comment] 2021-08-30 13:57
@paulmillr Since it's not a bug in .mobileconfig file I ask this issue be closed.
We cannot fix it only apple can so I vote to close it but it's up to you.

**Closed** 2021-08-30 14:07 UTC
